# Generated by Django 4.0.6 on 2022-07-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comments_options_remove_post_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='comments_id',
            field=models.ManyToManyField(blank=True, to='blog.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
