# Generated by Django 4.0.6 on 2022-07-24 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_post_comments_post_id_post_comments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_id',
            field=models.ManyToManyField(blank=True, related_name='comments', to='blog.comments'),
        ),
    ]
