# Generated by Django 4.0.6 on 2022-07-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comments_post_id_alter_post_comments_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_id',
        ),
        migrations.AddField(
            model_name='post',
            name='comments_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.comments'),
        ),
    ]
