# Generated by Django 4.0.6 on 2022-07-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_comments_id_post_comments_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
