# Generated by Django 4.0.6 on 2022-07-29 19:45

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
