# Generated by Django 4.0.6 on 2022-08-01 19:21

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=ckeditor.fields.RichTextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
