# Generated by Django 4.0.6 on 2022-08-01 19:22

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_comments_comment_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=ckeditor.fields.RichTextField(max_length=150, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
